<?php
class Entity_Constant {
 	protected $currency = array("EUR" => 'euro','USD'=> 'dollar US','GBP'=> 'livre sterling','CHF'=> 'franc suisse','CAD'=> 'dollar canadien','AUD'=> 'dollar australien','NZD'=> 'dollar néo-zélandais','JPY'=> 'yen japonais','HKD'=> 'dollar de Hong Kong','CNY'=> 'yuan chinois','RUB'=> 'rouble russe','THB'=> 'baht thaïlandais','DKK'=>'couronne danoise','NOK'=> 'couronne norvégienne','SEK'=> 'couronne suédoise','CZK'=> 'couronne tchèque','SGD'=> 'dollar singapourien','HUF'=> 'forint hongrois','HRK'=> 'kuna croate','LVL'=> 'lats letton','RON'=> 'leu roumain','BGN'=> 'lev bulgare','LTL'=> 'litas lituanien','TRY'=> 'livre turque','MXN'=> 'peso mexicain','PHP'=> 'peso philippin','ZAR'=> 'rand sud africain','BRL'=> 'réal brésilien','MYR'=> 'ringgit malésien','INR'=> 'roupie indienne','IDR'=> 'roupie indonésienne','ILS'=> 'shekel israélien','KRW'=> 'won de Corée du Sud','PLN'=> 'zloty polonais','XAF'=> 'franc CFA (XAF)','XOF'=> 'franc CFA (XOF)','XPF'=> 'franc CFP (XPF)');
 	protected $payment_mode = array("0" => 'Non payé','2' => 'Carte bancaire','4' => 'Chèque','3' => 'Virement','5' => 'Espèces','1' => 'Paypal','8' => 'Prélèvement','9' => 'TIP (Titre interbancaire de paiement)','30' => 'Ticket restaurant','31' => 'Chèque cadeau','32' => 'Chèque vacances','50' => 'LCR (Lettre de change relevé)','51' => 'BOR (Billet à ordre relevé)','99' => 'Autre','999' => 'Créance irrécouvrable');
 	protected $vat_exemption_reason = array('20' => 'art. 259 A.2 du CGI','30' => 'art. 259 A.5 du CGI','40' => 'art. 259 B du CGI','10' => 'art. 259.1 du CGI','60' => 'art. 262 I du CGI','50' => 'art. 262 ter 1 du CGI','70' => 'art. 283.2 du CGI','100' => 'art. 293 B du CGI','1' => 'Autoliquidation');
 	protected $pay_before = array('0' => 'Comptant','15' => '15 jours nets','30' => '30 jours nets','45' => '45 jours nets','60' => '60 jours nets','7fm' => '7 jours fin de mois','30fm' => '30 jours fin de mois','45fm' => '45 jours fin de mois','0fm10' => 'fin de mois le 10','0fm20' => 'fin de mois le 20','30fm10' => '30 jours fin de mois le 10','30fm20' => '30 jours fin de mois le 20');
 	protected $language = array("fr" => "Français",'en'=>'Anglais');
 	protected $nature = array("1" => "Vente",'2'=>'BIC - Prestations de service commerciales ou artisanales','3'=> 'BNC - Prestation non commerciale','9'=> 'Non applicable');
 	protected $civility = array("M."=>'Monsieur','Mme'=>'Madame','Mlle'=>'Mademoiselle','Dr'=>'Docteur','Me'=>'Maître','Pr'=>'Professeur');
 	protected $followup_status = array("0"=>'Devis/Factures','1'=>'Devis uniquement','2'=>'Factures uniquement');
 	protected $quote_status = array("0"=>'En attente','1'=>'Accepté','9'=>'Refusé');
 	protected $category_status = array("0"=>'Achats/Ventes','1'=>'Achats uniquement','2'=>'Ventes uniquement'); 	
}
?>