<?php
namespace FacturationPro\Entity;

/**
 * Created by PhpStorm.
 * User: remi
 * Date: 12/28/16
 * Time: 11:00 PM
 */
class Country
{
    /** @var  \FacturationPro\FacturationPro */
    protected $master;

    /** @var  string */
    protected $reference;

    /** @var  string */
    protected $title;

    CONST COUNTRY_AFGHANISTAN = "AF";
    CONST COUNTRY_ALAND_ISLANDS = "AX";
    CONST COUNTRY_ALBANIA = "AL";
    CONST COUNTRY_ALGERIA = "DZ";
    CONST COUNTRY_AMERICAN_SAMOA = "AS";
    CONST COUNTRY_ANDORRA = "AD";
    CONST COUNTRY_ANGOLA = "AO";
    CONST COUNTRY_ANGUILLA = "AI";
    CONST COUNTRY_ANTARCTICA = "AQ";
    CONST COUNTRY_ANTIGUA_AND_BARBUDA = "AG";
    CONST COUNTRY_ARGENTINA = "AR";
    CONST COUNTRY_ARMENIA = "AM";
    CONST COUNTRY_ARUBA = "AW";
    CONST COUNTRY_AUSTRALIA = "AU";
    CONST COUNTRY_AUSTRIA = "AT";
    CONST COUNTRY_AZERBAIJAN = "AZ";
    CONST COUNTRY_BAHAMAS = "BS";
    CONST COUNTRY_BAHRAIN = "BH";
    CONST COUNTRY_BANGLADESH = "BD";
    CONST COUNTRY_BARBADOS = "BB";
    CONST COUNTRY_BELARUS = "BY";
    CONST COUNTRY_BELGIUM = "BE";
    CONST COUNTRY_BELIZE = "BZ";
    CONST COUNTRY_BENIN = "BJ";
    CONST COUNTRY_BERMUDA = "BM";
    CONST COUNTRY_BHUTAN = "BT";
    CONST COUNTRY_BOLIVIA = "BO";
    CONST COUNTRY_BOSNIA_AND_HERZEGOVINA = "BA";
    CONST COUNTRY_BOTSWANA = "BW";
    CONST COUNTRY_BOUVET_ISLAND = "BV";
    CONST COUNTRY_BRAZIL = "BR";
    CONST COUNTRY_BRITISH_INDIAN_OCEAN_TERRITORY = "IO";
    CONST COUNTRY_BRUNEI_DARUSSALAM = "BN";
    CONST COUNTRY_BULGARIA = "BG";
    CONST COUNTRY_BURKINA_FASO = "BF";
    CONST COUNTRY_BURUNDI = "BI";
    CONST COUNTRY_CAMBODIA = "KH";
    CONST COUNTRY_CAMEROON = "CM";
    CONST COUNTRY_CANADA = "CA";
    CONST COUNTRY_CAPE_VERDE = "CV";
    CONST COUNTRY_CAYMAN_ISLANDS = "KY";
    CONST COUNTRY_CENTRAL_AFRICAN_REPUBLIC = "CF";
    CONST COUNTRY_CHAD = "TD";
    CONST COUNTRY_CHILE = "CL";
    CONST COUNTRY_CHINA = "CN";
    CONST COUNTRY_CHRISTMAS_ISLAND = "CX";
    CONST COUNTRY_COCOS__KEELING__ISLANDS = "CC";
    CONST COUNTRY_COLOMBIA = "CO";
    CONST COUNTRY_COMOROS = "KM";
    CONST COUNTRY_CONGO = "CG";
    CONST COUNTRY_CONGO__DEMOCRATIC_REPUBLIC = "CD";
    CONST COUNTRY_COOK_ISLANDS = "CK";
    CONST COUNTRY_COSTA_RICA = "CR";
    CONST COUNTRY_COTE_D_IVOIRE = "CI";
    CONST COUNTRY_CROATIA = "HR";
    CONST COUNTRY_CUBA = "CU";
    CONST COUNTRY_CYPRUS = "CY";
    CONST COUNTRY_CZECH_REPUBLIC = "CZ";
    CONST COUNTRY_DENMARK = "DK";
    CONST COUNTRY_DJIBOUTI = "DJ";
    CONST COUNTRY_DOMINICA = "DM";
    CONST COUNTRY_DOMINICAN_REPUBLIC = "DO";
    CONST COUNTRY_ECUADOR = "EC";
    CONST COUNTRY_EGYPT = "EG";
    CONST COUNTRY_EL_SALVADOR = "SV";
    CONST COUNTRY_EQUATORIAL_GUINEA = "GQ";
    CONST COUNTRY_ERITREA = "ER";
    CONST COUNTRY_ESTONIA = "EE";
    CONST COUNTRY_ETHIOPIA = "ET";
    CONST COUNTRY_FALKLAND_ISLANDS__MALVINAS_ = "FK";
    CONST COUNTRY_FAROE_ISLANDS = "FO";
    CONST COUNTRY_FIJI = "FJ";
    CONST COUNTRY_FINLAND = "FI";
    CONST COUNTRY_FRANCE = "FR";
    CONST COUNTRY_FRENCH_GUIANA = "GF";
    CONST COUNTRY_FRENCH_POLYNESIA = "PF";
    CONST COUNTRY_FRENCH_SOUTHERN_TERRITORIES = "TF";
    CONST COUNTRY_GABON = "GA";
    CONST COUNTRY_GAMBIA = "GM";
    CONST COUNTRY_GEORGIA = "GE";
    CONST COUNTRY_GERMANY = "DE";
    CONST COUNTRY_GHANA = "GH";
    CONST COUNTRY_GIBRALTAR = "GI";
    CONST COUNTRY_GREECE = "GR";
    CONST COUNTRY_GREENLAND = "GL";
    CONST COUNTRY_GRENADA = "GD";
    CONST COUNTRY_GUADELOUPE = "GP";
    CONST COUNTRY_GUAM = "GU";
    CONST COUNTRY_GUATEMALA = "GT";
    CONST COUNTRY_GUERNSEY = "GG";
    CONST COUNTRY_GUINEA = "GN";
    CONST COUNTRY_GUINEA_BISSAU = "GW";
    CONST COUNTRY_GUYANA = "GY";
    CONST COUNTRY_HAITI = "HT";
    CONST COUNTRY_HEARD_ISLAND___MCDONALD_ISLANDS = "HM";
    CONST COUNTRY_HOLY_SEE__VATICAN_CITY_STATE_ = "VA";
    CONST COUNTRY_HONDURAS = "HN";
    CONST COUNTRY_HONG_KONG = "HK";
    CONST COUNTRY_HUNGARY = "HU";
    CONST COUNTRY_ICELAND = "IS";
    CONST COUNTRY_INDIA = "IN";
    CONST COUNTRY_INDONESIA = "ID";
    CONST COUNTRY_IRAN__ISLAMIC_REPUBLIC_OF = "IR";
    CONST COUNTRY_IRAQ = "IQ";
    CONST COUNTRY_IRELAND = "IE";
    CONST COUNTRY_ISLE_OF_MAN = "IM";
    CONST COUNTRY_ISRAEL = "IL";
    CONST COUNTRY_ITALY = "IT";
    CONST COUNTRY_JAMAICA = "JM";
    CONST COUNTRY_JAPAN = "JP";
    CONST COUNTRY_JERSEY = "JE";
    CONST COUNTRY_JORDAN = "JO";
    CONST COUNTRY_KAZAKHSTAN = "KZ";
    CONST COUNTRY_KENYA = "KE";
    CONST COUNTRY_KIRIBATI = "KI";
    CONST COUNTRY_KOREA = "KR";
    CONST COUNTRY_KUWAIT = "KW";
    CONST COUNTRY_KYRGYZSTAN = "KG";
    CONST COUNTRY_LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC = "LA";
    CONST COUNTRY_LATVIA = "LV";
    CONST COUNTRY_LEBANON = "LB";
    CONST COUNTRY_LESOTHO = "LS";
    CONST COUNTRY_LIBERIA = "LR";
    CONST COUNTRY_LIBYAN_ARAB_JAMAHIRIYA = "LY";
    CONST COUNTRY_LIECHTENSTEIN = "LI";
    CONST COUNTRY_LITHUANIA = "LT";
    CONST COUNTRY_LUXEMBOURG = "LU";
    CONST COUNTRY_MACAO = "MO";
    CONST COUNTRY_MACEDONIA = "MK";
    CONST COUNTRY_MADAGASCAR = "MG";
    CONST COUNTRY_MALAWI = "MW";
    CONST COUNTRY_MALAYSIA = "MY";
    CONST COUNTRY_MALDIVES = "MV";
    CONST COUNTRY_MALI = "ML";
    CONST COUNTRY_MALTA = "MT";
    CONST COUNTRY_MARSHALL_ISLANDS = "MH";
    CONST COUNTRY_MARTINIQUE = "MQ";
    CONST COUNTRY_MAURITANIA = "MR";
    CONST COUNTRY_MAURITIUS = "MU";
    CONST COUNTRY_MAYOTTE = "YT";
    CONST COUNTRY_MEXICO = "MX";
    CONST COUNTRY_MICRONESIA__FEDERATED_STATES_OF = "FM";
    CONST COUNTRY_MOLDOVA = "MD";
    CONST COUNTRY_MONACO = "MC";
    CONST COUNTRY_MONGOLIA = "MN";
    CONST COUNTRY_MONTENEGRO = "ME";
    CONST COUNTRY_MONTSERRAT = "MS";
    CONST COUNTRY_MOROCCO = "MA";
    CONST COUNTRY_MOZAMBIQUE = "MZ";
    CONST COUNTRY_MYANMAR = "MM";
    CONST COUNTRY_NAMIBIA = "NA";
    CONST COUNTRY_NAURU = "NR";
    CONST COUNTRY_NEPAL = "NP";
    CONST COUNTRY_NETHERLANDS = "NL";
    CONST COUNTRY_NETHERLANDS_ANTILLES = "AN";
    CONST COUNTRY_NEW_CALEDONIA = "NC";
    CONST COUNTRY_NEW_ZEALAND = "NZ";
    CONST COUNTRY_NICARAGUA = "NI";
    CONST COUNTRY_NIGER = "NE";
    CONST COUNTRY_NIGERIA = "NG";
    CONST COUNTRY_NIUE = "NU";
    CONST COUNTRY_NORFOLK_ISLAND = "NF";
    CONST COUNTRY_NORTHERN_MARIANA_ISLANDS = "MP";
    CONST COUNTRY_NORWAY = "NO";
    CONST COUNTRY_OMAN = "OM";
    CONST COUNTRY_PAKISTAN = "PK";
    CONST COUNTRY_PALAU = "PW";
    CONST COUNTRY_PALESTINIAN_TERRITORY__OCCUPIED = "PS";
    CONST COUNTRY_PANAMA = "PA";
    CONST COUNTRY_PAPUA_NEW_GUINEA = "PG";
    CONST COUNTRY_PARAGUAY = "PY";
    CONST COUNTRY_PERU = "PE";
    CONST COUNTRY_PHILIPPINES = "PH";
    CONST COUNTRY_PITCAIRN = "PN";
    CONST COUNTRY_POLAND = "PL";
    CONST COUNTRY_PORTUGAL = "PT";
    CONST COUNTRY_PUERTO_RICO = "PR";
    CONST COUNTRY_QATAR = "QA";
    CONST COUNTRY_REUNION = "RE";
    CONST COUNTRY_ROMANIA = "RO";
    CONST COUNTRY_RUSSIAN_FEDERATION = "RU";
    CONST COUNTRY_RWANDA = "RW";
    CONST COUNTRY_SAINT_BARTHELEMY = "BL";
    CONST COUNTRY_SAINT_HELENA = "SH";
    CONST COUNTRY_SAINT_KITTS_AND_NEVIS = "KN";
    CONST COUNTRY_SAINT_LUCIA = "LC";
    CONST COUNTRY_SAINT_MARTIN = "MF";
    CONST COUNTRY_SAINT_PIERRE_AND_MIQUELON = "PM";
    CONST COUNTRY_SAINT_VINCENT_AND_GRENADINES = "VC";
    CONST COUNTRY_SAMOA = "WS";
    CONST COUNTRY_SAN_MARINO = "SM";
    CONST COUNTRY_SAO_TOME_AND_PRINCIPE = "ST";
    CONST COUNTRY_SAUDI_ARABIA = "SA";
    CONST COUNTRY_SENEGAL = "SN";
    CONST COUNTRY_SERBIA = "RS";
    CONST COUNTRY_SEYCHELLES = "SC";
    CONST COUNTRY_SIERRA_LEONE = "SL";
    CONST COUNTRY_SINGAPORE = "SG";
    CONST COUNTRY_SLOVAKIA = "SK";
    CONST COUNTRY_SLOVENIA = "SI";
    CONST COUNTRY_SOLOMON_ISLANDS = "SB";
    CONST COUNTRY_SOMALIA = "SO";
    CONST COUNTRY_SOUTH_AFRICA = "ZA";
    CONST COUNTRY_SOUTH_GEORGIA_AND_SANDWICH_ISL_ = "GS";
    CONST COUNTRY_SPAIN = "ES";
    CONST COUNTRY_SRI_LANKA = "LK";
    CONST COUNTRY_SUDAN = "SD";
    CONST COUNTRY_SURINAME = "SR";
    CONST COUNTRY_SVALBARD_AND_JAN_MAYEN = "SJ";
    CONST COUNTRY_SWAZILAND = "SZ";
    CONST COUNTRY_SWEDEN = "SE";
    CONST COUNTRY_SWITZERLAND = "CH";
    CONST COUNTRY_SYRIAN_ARAB_REPUBLIC = "SY";
    CONST COUNTRY_TAIWAN = "TW";
    CONST COUNTRY_TAJIKISTAN = "TJ";
    CONST COUNTRY_TANZANIA = "TZ";
    CONST COUNTRY_THAILAND = "TH";
    CONST COUNTRY_TIMOR_LESTE = "TL";
    CONST COUNTRY_TOGO = "TG";
    CONST COUNTRY_TOKELAU = "TK";
    CONST COUNTRY_TONGA = "TO";
    CONST COUNTRY_TRINIDAD_AND_TOBAGO = "TT";
    CONST COUNTRY_TUNISIA = "TN";
    CONST COUNTRY_TURKEY = "TR";
    CONST COUNTRY_TURKMENISTAN = "TM";
    CONST COUNTRY_TURKS_AND_CAICOS_ISLANDS = "TC";
    CONST COUNTRY_TUVALU = "TV";
    CONST COUNTRY_UGANDA = "UG";
    CONST COUNTRY_UKRAINE = "UA";
    CONST COUNTRY_UNITED_ARAB_EMIRATES = "AE";
    CONST COUNTRY_UNITED_KINGDOM = "GB";
    CONST COUNTRY_UNITED_STATES = "US";
    CONST COUNTRY_UNITED_STATES_OUTLYING_ISLANDS = "UM";
    CONST COUNTRY_URUGUAY = "UY";
    CONST COUNTRY_UZBEKISTAN = "UZ";
    CONST COUNTRY_VANUATU = "VU";
    CONST COUNTRY_VENEZUELA = "VE";
    CONST COUNTRY_VIET_NAM = "VN";
    CONST COUNTRY_VIRGIN_ISLANDS__BRITISH = "VG";
    CONST COUNTRY_VIRGIN_ISLANDS__U_S_ = "VI";
    CONST COUNTRY_WALLIS_AND_FUTUNA = "WF";
    CONST COUNTRY_WESTERN_SAHARA = "EH";
    CONST COUNTRY_YEMEN = "YE";
    CONST COUNTRY_ZAMBIA = "ZM";
    CONST COUNTRY_ZIMBABWE = "ZW";

    private $list = array
    (
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island & Mcdonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle Of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KR' => 'Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia And Sandwich Isl.',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe'
    );

    /** @var string $reference */
    public function __construct($reference)
    {
        $this->reference = $reference;
    }

    public function getReference()
    {
        return $this->reference;
    }

    public function getTitle()
    {
        return $this->list[$this->reference];
    }
}